import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    // Default to 'EN' (English)
    const [language, setLanguage] = useState(localStorage.getItem('gavran_lang') || 'EN');

    useEffect(() => {
        localStorage.setItem('gavran_lang', language);
    }, [language]);

    const translations = {
        EN: {
            nav_home: "Home",
            nav_shop: "Shop",
            nav_cart: "Cart",
            nav_track: "Track Order",
            nav_signin: "Sign In",
            nav_logout: "Logout",
            nav_profile: "Profile",
            hero_title: "Authentic Taste of Maharashtra",
            hero_subtitle: "Experience the joy of handmade Vermicelli, crispy Kurdai, and traditional Papad delivered straight to your doorstep.",
            shop_now: "Shop Now",
            learn_more: "Learn More",
            feature_natural: "100% Natural",
            feature_natural_desc: "Our Kurdai and Papad are made with zero chemicals, using only high-quality locally sourced wheat and spices.",
            feature_rural: "Rural Craftsmanship",
            feature_rural_desc: "Prepared with love by women artisans in Shrigonda, preserving generations-old traditional recipes.",
            feature_fresh: "Fresh to Doorstep",
            feature_fresh_desc: "Fast, reliable delivery across all of Maharashtra, ensuring you get the freshest handmade delicacies.",
            footer_copyright: "© 2024 Gavran Magic. All rights reserved.",
            promo_msg_offer: "Get FREE Delivery on your first 2 orders!",
            special_offer: "Special Offer",
            footer_desc: "Authentic, handmade Maharashtrian delicacies delivered straight from our kitchen to your door. Taste the tradition in every bite.",
            stay_connected: "Stay Connected",
            newsletter_desc: "Subscribe to our newsletter for exclusive offers, recipes, and discounts!",
            email_placeholder: "Your Email Address",
            testimonials_title: "What Our Customers Say",
            testimonial_1_name: "Sneha Deshmukh",
            testimonial_1_text: "The Kurdai is just like how my grandmother used to make! So crispy and fresh.",
            testimonial_2_name: "Rahul Patil",
            testimonial_2_text: "Best handmade Shevai in Maharashtra. Fast delivery and great packaging.",
            testimonial_3_name: "Priya Kulkarni",
            testimonial_3_text: "Authentic taste and zero chemicals. My kids love the Papad!",
            view_all: "View All Products",
            featured_title: "Featured Delicacies",
            featured_subtitle: "Handpicked traditional favorites from our kitchen to yours.",
            availability: "Availability",
            in_stock: "In Stock",
            out_of_stock: "Out of Stock",
            insight: "Product Insight",
            ingredients: "Key Ingredients",
            instructions: "How to Prepare",
            add_to_cart: "Add to Cart",
            buy_now: "Buy Now",
            share_product: "Share Product",
            feedback_title: "Customer Feedback",
            post_review: "Post Review",
            review_headline: "Review Headline",
            write_review: "Write your review here...",
            upload_photo: "Upload Photo",
            change_photo: "Change Photo",
            my_profile: "My Profile",
            order_history: "Order History",
            personal_info: "Personal Information",
            complete_profile: "Complete Your Profile",
            profile_subtitle: "Update your shipping and contact details below",
            full_name: "Full Name",
            email_addr: "Email Address (Optional)",
            delivery_addr: "Delivery Address",
            city: "City",
            pincode: "Pincode",
            update_details: "Update Details",
            saving: "Saving Changes...",
            no_orders: "No Orders Yet",
            track: "Track",
            placed_on: "Placed on",
            total: "Total",
            shop_title: "Our Traditional Kitchen",
            shop_subtitle: "Authentic handmade Maharashtrian delicacies prepared with love and tradition.",
            search_placeholder: "Search for Kurdai, Papad, Masala...",
            server_waking: "Server is starting up...",
            server_waking_msg: "Our traditional kitchen is preparing the catalog. Please wait ~30 seconds. ☕",
            product_not_available: "Product is Currently Not Available",
            preparing_fresh_stock: "We are currently preparing fresh stock. Try checking \"All\" products.",
            cat_all: "All",
            cat_kurdai: "Handmade Kurdai",
            cat_papad: "Traditional Papad",
            cat_shevai: "Vermicelli (Shevai)",
            cat_masalas: "Traditional Masalas",
            cart_title: "Your Cart",
            cart_empty: "Your Cart is Empty",
            cart_empty_msg: "Looks like you haven't added any magic to your cart yet.",
            start_shopping: "Start Shopping",
            cart_product: "Product",
            cart_price: "Price",
            cart_quantity: "Quantity",
            cart_subtotal: "Subtotal",
            continue_shopping: "Continue Shopping",
            order_summary: "Order Summary",
            shipping_at_checkout: "Calculated at checkout",
            proceed_checkout: "Proceed to Checkout",
            secure_checkout: "Secure Checkout",
            remove_unavailable: "Please remove unavailable products before checking out.",
            product_unavailable_cart: "Product is Unavailable",
            checkout_title: "Complete Your Order",
            checkout_subtitle: "Join thousands of happy customers enjoying the authentic magic of Maharashtrian kitchen.",
            step_contact: "Contact Information",
            step_shipping: "Shipping Details",
            step_payment: "Payment Method",
            home_addr: "Home Address",
            gps_loc: "GPS Location",
            new_addr: "New Address",
            detect_loc: "Detect location",
            detecting: "Detecting...",
            save_to_profile: "Save this to my profile",
            upi_pay: "UPI / Online Pay",
            cod: "Cash on Delivery",
            bag_summary: "Bag Summary",
            shipping_cost: "Shipping Cost",
            calculating: "Calculating...",
            enter_pin: "Enter PIN",
            place_order: "Place Secure Order",
            confirming_order: "Confirming Order...",
            ssl_checkout: "SSL SECURE CHECKOUT",
            only_left: "Only {count} products available!",
            total_reviews: "{count} Total Reviews",
            related_products: "Related Products",
            delivery_maharashtra: "Delivery across all of Maharashtra"
        },
        MR: {
            nav_home: "होम",
            nav_shop: "खरेदी",
            nav_cart: "कार्ट",
            nav_track: "ऑर्डर ट्रॅक करा",
            nav_signin: "लॉगिन करा",
            nav_logout: "लॉगआउट",
            nav_profile: "प्रोफाइल",
            hero_title: "महाराष्ट्राची अस्सल चव",
            hero_subtitle: "हस्तशिल्पित शेवया, कुरकुरीत कुरडई आणि पारंपारिक पापडांचा आनंद घ्या, थेट तुमच्या दारापर्यंत.",
            shop_now: "आता खरेदी करा",
            learn_more: "अधिक जाणून घ्या",
            feature_natural: "१००% नैसर्गिक",
            feature_natural_desc: "आमची कुरडई आणि पापड शून्य रसायने वापरून, फक्त उच्च दर्जाचे देशी गहू आणि मसाल्यांपासून बनवले जातात.",
            feature_rural: "ग्रामीण कारागिरी",
            feature_rural_desc: "श्रीगोंद्यातील महिला कारागिरांनी प्रेमाने तयार केलेले, पिढ्यानपिढ्या जुन्या पारंपारिक पाककृती जपून.",
            feature_fresh: "ताजे तुमच्या दारापर्यंत",
            feature_fresh_desc: "संपूर्ण महाराष्ट्रात जलद आणि विश्वासार्ह डिलिव्हरी, तुम्हाला ताजे हस्तनिर्मित पदार्थ मिळतील याची खात्री देतो.",
            footer_copyright: "© २०२४ गावरान मॅजिक. सर्व हक्क राखीव.",
            promo_msg_offer: "तुमच्या पहिल्या २ ऑर्डर्सवर मोफत डिलिव्हरी मिळवा!",
            special_offer: "विशेष ऑफर",
            footer_desc: "आमच्या स्वयंपाकघरातून अ अस्सल, हस्तनिर्मित महाराष्ट्रीयन पदार्थ थेट तुमच्या दारापर्यंत. प्रत्येक घासात परंपरेची चव.",
            stay_connected: "संपर्कात रहा",
            newsletter_desc: "आमची आकर्षक ऑफर, रेसिपी आणि डिस्काउंट मिळवण्यासाठी ईमेल सबस्क्राइब करा!",
            email_placeholder: "तुमचा ईमेल पत्ता",
            testimonials_title: "आमचे ग्राहक काय म्हणतात",
            testimonial_1_name: "स्नेहा देशमुख",
            testimonial_1_text: "कुरडई अगदी माझ्या आजीने बनवल्यासारखीच आहे! खूप कुरकुरीत आणि ताजी.",
            testimonial_2_name: "राहुल पाटील",
            testimonial_2_text: "महाराष्ट्रातील सर्वोत्तम हस्तनिर्मित शेवया. जलद डिलिव्हरी आणि उत्तम पॅकेजिंग.",
            testimonial_3_name: "प्रिया कुलकर्णी",
            testimonial_3_text: "अस्सल चव आणि झीरो केमिकल्स. माझ्या मुलांना पापड खूप आवडतात!",
            view_all: "सर्व उत्पादने पहा",
            featured_title: "आमचे लोकप्रिय पदार्थ",
            featured_subtitle: "आमच्या स्वयंपाकघरातील काही खास आणि निवडक पदार्थ.",
            availability: "उपलब्धता",
            in_stock: "उपलब्ध आहे",
            out_of_stock: "उपलब्ध नाही",
            insight: "उत्पादनाची माहिती",
            ingredients: "साहित्य",
            instructions: "बनवण्याची पद्धत",
            add_to_cart: "कार्टमध्ये टाका",
            buy_now: "आता खरेदी करा",
            share_product: "उत्पादन शेअर करा",
            feedback_title: "ग्राहकांचे अभिप्राय",
            post_review: "प्रतिक्रिया पाठवा",
            review_headline: "प्रतिक्रियेचे शीर्षक",
            write_review: "तुमची प्रतिक्रिया येथे लिहा...",
            upload_photo: "फोटो अपलोड करा",
            change_photo: "फोटो बदला",
            my_profile: "माझी प्रोफाइल",
            order_history: "मागील ऑर्डर्स",
            personal_info: "वैयक्तिक माहिती",
            complete_profile: "प्रोफाइल पूर्ण करा",
            profile_subtitle: "तुमचा पत्ता आणि संपर्क तपशील अपडेट करा",
            full_name: "पूर्ण नाव",
            email_addr: "ईमेल पत्ता (पर्यायी)",
            delivery_addr: "डिलिव्हरी पत्ता",
            city: "शहर",
            pincode: "पिनकोड",
            update_details: "माहिती जतन करा",
            saving: "जतन होत आहे...",
            no_orders: "अजून एकही ऑर्डर नाही",
            track: "ट्रॅक करा",
            placed_on: "ऑर्डर दिनांक",
            total: "एकूण",
            shop_title: "आमचे पारंपारिक स्वयंपाकघर",
            shop_subtitle: "प्रेम आणि परंपरेने तयार केलेले अस्सल हस्तनिर्मित महाराष्ट्रीयन पदार्थ.",
            search_placeholder: "कुरडई, पापड, मसाला शोधा...",
            server_waking: "सर्व्हर सुरू होत आहे...",
            server_waking_msg: "आमचे पारंपारिक स्वयंपाकघर कॅटलॉग तयार करत आहे. कृपया ३० सेकंद प्रतीक्षा करा. ☕",
            product_not_available: "उत्पादन सध्या उपलब्ध नाही",
            preparing_fresh_stock: "आम्ही सध्या नवीन स्टॉक तयार करत आहोत. 'सर्व' उत्पादने तपासून पहा.",
            cat_all: "सर्व",
            cat_kurdai: "हस्तनिर्मित कुरडई",
            cat_papad: "पारंपारिक पापड",
            cat_shevai: "शेवई",
            cat_masalas: "पारंपारिक मसाले",
            cart_title: "तुमचे कार्ट",
            cart_empty: "तुमचे कार्ट रिकामे आहे",
            cart_empty_msg: "असे दिसते की तुम्ही अजून तुमच्या कार्टमध्ये काहीही टाकले नाही.",
            start_shopping: "खरेदी सुरू करा",
            cart_product: "उत्पादन",
            cart_price: "किंमत",
            cart_quantity: "प्रमाण",
            cart_subtotal: "एकूण",
            continue_shopping: "खरेदी सुरू ठेवा",
            order_summary: "ऑर्डर सारांश",
            shipping_at_checkout: "चेकआउट वेळी मोजले जाईल",
            proceed_checkout: "चेकआउट करा",
            secure_checkout: "सुरक्षित चेकआउट",
            remove_unavailable: "कृपया पुढे जाण्यापूर्वी अनुपलब्ध उत्पादने काढून टाका.",
            product_unavailable_cart: "उत्पादन अनुपलब्ध आहे",
            checkout_title: "तुमची ऑर्डर पूर्ण करा",
            checkout_subtitle: "महाराष्ट्रीयन स्वयंपाकघरातील अस्सल चवीचा आनंद घेणाऱ्या हजारो आनंदी ग्राहकांमध्ये सामील व्हा.",
            step_contact: "संपर्क माहिती",
            step_shipping: "डिलिव्हरी तपशील",
            step_payment: "पेमेंट पद्धत",
            home_addr: "घरचा पत्ता",
            gps_loc: "जीपीएस लोकेशन",
            new_addr: "नवीन पत्ता",
            detect_loc: "लोकेशन शोधा",
            detecting: "शोधत आहे...",
            save_to_profile: "हे माझ्या प्रोफाइलमध्ये जतन करा",
            upi_pay: "UPI / ऑनलाइन पेमेंट",
            cod: "कॅश ऑन डिलिव्हरी",
            bag_summary: "ऑर्डर सारांश",
            shipping_cost: "डिलिव्हरी शुल्क",
            calculating: "मोजत आहे...",
            enter_pin: "पिनकोड टाका",
            place_order: "ऑर्डर द्या",
            confirming_order: "ऑर्डर जतन होत आहे...",
            ssl_checkout: "सुरक्षित चेकआउट",
            only_left: "फक्त {count} शिल्लक!",
            total_reviews: "एकूण {count} प्रतिक्रिया",
            related_products: "संबंधित उत्पादने",
            delivery_maharashtra: "संपूर्ण महाराष्ट्रात डिलिव्हरी"
        }
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
